# Generated by Django 4.1.2 on 2022-10-19 12:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='имя')),
                ('email', models.CharField(max_length=24, verbose_name='почта')),
                ('message', models.CharField(max_length=256, verbose_name='сообщение')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 12, 15, 52, 45024), verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
                'db_table': 'blog_contacts',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='заголовок')),
                ('subtitle', models.CharField(max_length=32, verbose_name='подзаголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 12, 15, 52, 42931), verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='картинка')),
                ('body', models.TextField(verbose_name='текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'db_table': 'blog_posts',
                'ordering': ('date_created',),
            },
        ),
    ]
